### ISSUE TITLE
How to active on register and login form

### ISSUE THREAD

**Issue by Misagh90** [UndefinedOffset/silverstripe-nocaptcha#24]
Hi,
how we can active this module on register and login page (Member Profile Module)?
where we can add these code:
`$form->enableSpamProtection()
    ->fields()->fieldByName('Captcha')
    ->setTitle("Spam protection")
    ->setDescription("Please tick the box to prove you're a human and help us stop spam.");`

Thanks,

**Comment by UndefinedOffset** [comment]
I believe you would need to do a subclass of the [MemberLoginForm](https://github.com/silverstripe/silverstripe-framework/blob/3.4/security/MemberLoginForm.php). Probably something similar to (untested):

```php
class NocaptchaLoginForm extends MemberLoginForm {
    public function __construct($controller, $name, $fields = null, $actions = null, $checkCurrentUser = true) {
        parent::__construct($controller, $name, $fields, $actions, $checkCurrentUser);
        
        
        if($checkCurrentUser && !Member::currentUser() && !Member::logged_in_session_exists()) {
            $this->enableSpamProtection();
            $this->Fields()
                    ->fieldByName('Captcha')
                        ->setTitle("Spam protection")
                        ->setDescription("Please tick the box to prove you're a human and help us stop spam.");
        }
    }
}
```

Then in your config do something like (again untested):
```yml
Injector:
    MemberLoginForm:
        class: "NocaptchaLoginForm"
```

I think that should work ;) give it a try and let me know.

**Comment by bigbang1980** [comment]
Thanks, it works like a charm
but im disable  'verify_ssl'

**Comment by Misagh90** [comment]
Thanks @UndefinedOffset 
it's working.

**Comment by UndefinedOffset** [comment]
Awesome, no problem
