### ISSUE TITLE
invisible recaptcha

### ISSUE THREAD

**Issue by guyvanbael** [UndefinedOffset/silverstripe-nocaptcha#30]
Hi would it be possible to use the latest invisible recaptcha. My guess is that a lot of website users would be very grateful ;-)

https://www.google.com/recaptcha/intro/invisible.html

**Comment by UndefinedOffset** [comment]
yep already supported in 0.3+ make sure your keys work for invisible and use the following in your yaml config. It can also be set on a per-field basis by calling ``setCaptchaSize('invisible')``.

```yml
NocaptchaField:
    default_size: "invisible"
```

**Comment by guyvanbael** [comment]
@UndefinedOffset  You're a legend ;-)

**Comment by UndefinedOffset** [comment]
I try ;), I'm going to close this issue
