### ISSUE TITLE
Getting it to show the reCAPTCHA

### ISSUE THREAD

**Issue by pinkp** [UndefinedOffset/silverstripe-nocaptcha#33]
I couldn't get this to work until adding **`"CommentingController::add_extension('CommentSpamProtection');"`**
to _config.php why isn't this mentioned in the instructions, is the .yaml file settings meant to be enough?

**Comment by UndefinedOffset** [comment]
The instructions don't cover working with the comments module they only cover working with just the SpamProtection module which covers all other forms that call ``enableSpamProtection()`` on the form. My guess that extension does that. I could add a note about the commenting module however.

**Comment by pinkp** [comment]
Oh ok, sorry its a little confusing. Yes a note would be nice! Thanks
