### ISSUE TITLE
ss4 compatibility

### ISSUE THREAD

**Issue by guyvanbael** [UndefinedOffset/silverstripe-nocaptcha#37]
Any plans on a version for SS4?

**Comment by UndefinedOffset** [comment]
Absolutely! Just a time game... maybe I'll start looking tomorrow.

**Comment by UndefinedOffset** [comment]
so I lied... I found some time give the 2.0.x branch a try, note you will need to use composer. Try the command below it should pull the 2.0.x branch:

```
composer require undefinedoffset/silverstripe-nocapcha ~2.0
```

**Comment by guyvanbael** [comment]
Great. It works like a charm!
Thanx for the hard work!

**Comment by UndefinedOffset** [comment]
It was actually pretty easy silverstripe/silverstripe-upgrader did 90% of the grunt work. That said this is a pretty simple module too :)
