### ISSUE TITLE
Composer.json dependencies for SS4

### ISSUE THREAD

**Issue by torindul** [UndefinedOffset/silverstripe-nocaptcha#41]
When calling the composer require for the nocaptcha module within SS4 it fails. To get around this I had to force my composer.json to use dev-master in order for your declared composer.json requirements to then pull the correct versions of silverstripe spamprotection module. Maybe a new branch could be made called 2.0 which is for SilverStripe 4.0 onwards?

**Comment by UndefinedOffset** [comment]
tag created :)
