### ISSUE TITLE
Adding nocaptcha field to page php

### ISSUE THREAD

**Issue by michael-harvey** [UndefinedOffset/silverstripe-nocaptcha#5]
Can this module be used for adding a nocaptcha field to a manual php form, or just userdefinedforms? I get an empty input returned when I add enablespamprotection to the form, and trying to add a NocaptchaField returns the same. Any help would be appreciated

**Comment by UndefinedOffset** [comment]
Did you resolve this? Was it just a flush required? Or?

**Comment by michael-harvey** [comment]
I changed the spamprotection module to 1.2.0 and after updating it worked perfectly. Not sure what was happening.

Thanks for making this module!

**Comment by UndefinedOffset** [comment]
Ya looks like that's the version [i set it for](https://github.com/UndefinedOffset/silverstripe-nocaptcha/blob/master/composer.json#L17). Glad that worked for you :)
