### ISSUE TITLE
Captcha is not showing in custom form please help

### ISSUE THREAD

**Issue by Bandnakalra** [UndefinedOffset/silverstripe-nocaptcha#51]

**Comment by UndefinedOffset** [comment]
are you calling `enableSpamProtection()` on the custom form as defined in the docs for the spam protection module (and in this one if I remember right) https://github.com/silverstripe/silverstripe-spamprotection#configuring ? Can you post some additional info like how the form is being constructed and your yaml config where you are setting the spam protector?

**Comment by Bandnakalra** [comment]
now the captcha is showing but i am getting error "Captcha is required" after submitting form

**Comment by UndefinedOffset** [comment]
Make sure you do not set the captcha to required, I know it sounds counter intuitive it's always required, that could be the issue there.

**Comment by Bandnakalra** [comment]
I am getting js error in console  
Cannot set property 'value' of null
    at DrawCaptcha 

Actually nocaptcha was taking path of its js file in my public/ resources/nocaptcha

so i put the js file in my public folder and captcha started showing up but not form submit getting error

**Comment by UndefinedOffset** [comment]
hmm what style of Recaptcha are you using and what version of this module are you using. As well are you using jQuery validate?
