### ISSUE TITLE
Working with Custom Forms

### ISSUE THREAD

**Issue by brycemurphy** [UndefinedOffset/silverstripe-nocaptcha#56]
Hi!

I'm working with your module for different types of forms on a site. It was easy enough to get Nocaptcha to work with User Forms and Comments, however I'm having big difficulties incorporating it with Custom Forms we're building. Do you know how to resolve this? It might be as easy as building out more on the backend, but I'm stumped myself.

Thanks.

**Comment by UndefinedOffset** [comment]
For custom forms you should be able to just call `$form->enableSpamProtection()` to add the spam protection via nocaptcha to your form. See the silverstripe/silverstripe-spamprotection documentation for more on how to do that.

Let me know how you make out :)

**Comment by brycemurphy** [comment]
Nope, simply putting `$form->enableSpamProtection` neither shows the box nor lets me submit legit forms. I know it *is* adding itself to the form by that command, but from what I can tell, it's not doing anything/not accepting the submissions.

**Comment by brycemurphy** [comment]
Got it, I wasn't including it in the page!
