### ISSUE TITLE
Issue adding spam protection field

### ISSUE THREAD

**Issue by TimStannard** [UndefinedOffset/silverstripe-nocaptcha#61]
Hey there! In the installation instructions it says "Finally, add the "spam protection" field to your form fields."

Which name do we call the field? See my Contactpage.php code below (not working)

        $fields = new FieldList( 
            new TextField('Name'), 
            new EmailField('Email'), 
            new TextareaField('Message')
           new SpamProtectionField('Captcha')
        );

**Comment by UndefinedOffset** [comment]
To do this simply call `->enableSpamProtection()` on the form object as the readme mentions later on. That should do what you need at least in the most common implementations.
