### ISSUE TITLE
not sure if this is working properly on V2

### ISSUE THREAD

**Issue by sunnysideup** [UndefinedOffset/silverstripe-nocaptcha#80]
I am looking here:

https://github.com/UndefinedOffset/silverstripe-nocaptcha/blob/master/src/Forms/NocaptchaField.php#L313-L316

I wonder:

a. when it is successful, `success` = 1, this means that `success` = 0 should be error?

b. if no `success` key is returned then it will not throw an error.

**Comment by UndefinedOffset** [comment]
I think `b` is a good point I've made an adjustment to account for that case however with `a` based on what I'm [reading here](https://developers.google.com/recaptcha/docs/verify) success is boolean true or false so I think that case is covered right.

**Comment by sunnysideup** [comment]
Great!  Thank you for looking at this.

**Comment by UndefinedOffset** [comment]
Tag coming soonish, waiting for SS5 to hit RC/find some time to confirm this works properly there. 99% sure it'll work just fine, I just haven't had the time to test 😄
