### ISSUE TITLE
Wrong configuration recommendation in error message, should be "NocaptchaField"

### ISSUE THREAD

**Issue by tiller1010** [UndefinedOffset/silverstripe-nocaptcha#84]
This error message gives the wrong configuration recommendation: https://github.com/UndefinedOffset/silverstripe-nocaptcha/blob/master/src/Forms/NocaptchaField.php#L197

It should be "NocaptchaField" instead of "Nocaptcha".

**Comment by UndefinedOffset** [comment]
Error message updated, thanks for pointing it out
